import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight, Check, ChevronDown, CreditCard, Heart, Menu, Minus, Plus, Search, ShoppingBag, Truck, X} from 'lucide-react';
import './styles.css';

const categories = [
  {id:'living', name:'Living room', en:'Living room'}, {id:'dining', name:'Dining room', en:'Dining room'},
  {id:'bedroom', name:'Bedroom', en:'Bedroom'}, {id:'decor', name:'Home decor', en:'Home decor'}
];
const seeds = ['Arc sofa','Linen lounge chair','Oak side table','Low media console','Soft ottoman','Round coffee table','Modular shelving','Boucle bench','Open bookcase','Woven floor cushion'];
const products = categories.flatMap((cat, ci) => seeds.map((name, i) => ({
  id:`${cat.id}-${i+1}`, category:cat.id, name, price: [468, 620, 395, 780, 340, 560, 720, 438, 685, 315][i], color:['sand','sage','clay','ink'][ci], number:i+1
})));
const money = n => `$${n.toLocaleString('en-US')}`;

function ProductArt({product, large=false}) { const x=(product.number-1)%5*25, y=Math.floor((product.number-1)/5)*100; return <div className={`product-art photo-art ${large?'large':''}`} style={{backgroundImage:`url('/images/${product.category}-catalog.png')`,backgroundPosition:`${x}% ${y}%`}}/> }

function Header({cartCount, onCart, onNavigate}) { return <>
  <div className="announce">Complimentary delivery on orders over $500 <ArrowRight size={14}/></div>
  <header><button className="icon-btn mobile-menu"><Menu size={20}/></button><button className="logo" onClick={()=>onNavigate('home')}>LVDONG<span>HOME</span></button>
  <nav>{categories.map(c=><button key={c.id} onClick={()=>onNavigate(c.id)}>{c.name}</button>)}<button onClick={()=>onNavigate('about')}>关于我们</button></nav>
  <div className="head-actions"><button className="icon-btn"><Search size={19}/></button><button className="icon-btn"><Heart size={19}/></button><button className="bag" onClick={onCart}><ShoppingBag size={19}/><b>{cartCount}</b></button></div></header>
</> }

function ProductCard({product, add}) { return <article className="product-card"><div className="card-art"><ProductArt product={product}/><button className="heart"><Heart size={17}/></button></div><div className="card-copy"><div><span className="eyebrow">{categories.find(c=>c.id===product.category).en}</span><h3>{product.name}</h3></div><strong>{money(product.price)}</strong></div><button className="text-add" onClick={()=>add(product)}>Add to Cart <Plus size={15}/></button></article> }

function Home({navigate, add}) { return <main>
  <section className="hero"><div className="hero-copy"><span className="eyebrow">THE EVERYDAY EDIT</span><h1>Room to live<br/><i>beautifully.</i></h1><p>Considered pieces for slow mornings, long dinners, and everything in between.</p><button className="btn dark" onClick={()=>navigate('shop')}>Shop the collection <ArrowRight size={17}/></button></div><div className="hero-photo"/></section>
  <section className="service-strip"><div><Truck/><span><b>Free delivery</b><small>On orders over $500</small></span></div><div><Check/><span><b>Thoughtful design</b><small>Made for everyday living</small></span></div><div><CreditCard/><span><b>Secure checkout</b><small>Pay safely online</small></span></div></section>
  <section className="section"><div className="section-top"><div><span className="eyebrow">SHOP BY ROOM</span><h2>Make space for good things.</h2></div><button className="link-btn" onClick={()=>navigate('shop')}>View all <ArrowRight size={15}/></button></div><div className="category-grid">{categories.map((c,i)=><button className={`category-tile tile-${i}`} onClick={()=>navigate(c.id)} key={c.id}><div className="category-photo" style={{backgroundImage:`url('/images/${c.id}-catalog.png')`}}/><span><small>{c.en}</small><b>{c.name}</b></span><ArrowRight size={19}/></button>)}</div></section>
  <section className="section cream"><div className="section-top"><div><span className="eyebrow">NEW ARRIVALS</span><h2>Pieces with presence.</h2></div><button className="link-btn" onClick={()=>navigate('shop')}>Shop new in <ArrowRight size={15}/></button></div><div className="product-grid">{products.slice(0,4).map(p=><ProductCard product={p} add={add} key={p.id}/>)}</div></section>
  <section className="editorial"><div className="editorial-art"/><div><span className="eyebrow">A QUIETER WAY HOME</span><h2>Designed to settle in.</h2><p>Natural textures, honest materials, and silhouettes that give your home room to breathe.</p><button className="btn outline" onClick={()=>navigate('about')}>Our design story <ArrowRight size={17}/></button></div></section>
 </main> }

function Shop({category, add}) { const list=category?products.filter(p=>p.category===category):products; return <main className="listing"><div className="listing-head"><span className="eyebrow">{category?categories.find(c=>c.id===category)?.en:'ALL COLLECTIONS'}</span><h1>{category?categories.find(c=>c.id===category)?.name:'Shop the collection'}</h1><p>Thoughtful furniture and home accents, made to be lived with.</p></div><div className="filter-row"><span>{list.length} pieces</span><button>Sort by <b>Featured</b><ChevronDown size={16}/></button></div><div className="product-grid">{list.map(p=><ProductCard product={p} add={add} key={p.id}/>)}</div></main> }

function CartDrawer({cart, close, update, checkout}) { const total=cart.reduce((s,x)=>s+x.price*x.qty,0); return <><div className={`scrim ${cart.length?'show':''}`} onClick={close}/><aside className={`cart-drawer ${cart.length?'open':''}`}><div className="drawer-head"><div><span className="eyebrow">YOUR BAG</span><h2>{cart.length} items</h2></div><button className="icon-btn" onClick={close}><X/></button></div>{cart.length?<><div className="cart-items">{cart.map(x=><div className="cart-item" key={x.id}><ProductArt product={x}/><div className="cart-info"><b>{x.name}</b><small>{money(x.price)}</small><div className="qty"><button onClick={()=>update(x.id,-1)}><Minus size={13}/></button><span>{x.qty}</span><button onClick={()=>update(x.id,1)}><Plus size={13}/></button></div></div></div>)}</div><div className="drawer-bottom"><div className="total"><span>Subtotal</span><b>{money(total)}</b></div><button className="btn dark wide" onClick={checkout}>Go to checkout <ArrowRight size={17}/></button><small className="muted">Taxes and delivery calculated at checkout.</small></div></>:<div className="empty"><ShoppingBag size={32}/><p>Your bag is waiting for something beautiful.</p></div>}</aside></> }

function Checkout({cart, navigate}) { const total=cart.reduce((s,x)=>s+x.price*x.qty,0); return <main className="checkout"><div className="checkout-main"><button className="back" onClick={()=>navigate('shop')}>← Continue shopping</button><span className="eyebrow">SECURE CHECKOUT</span><h1>Almost home.</h1><div className="steps"><span className="active">1. Details</span><span>2. Payment</span><span>3. Confirmation</span></div><div className="form-section"><h3>Contact details</h3><div className="fields"><input placeholder="Email address"/><input placeholder="Phone number"/></div></div><div className="form-section"><h3>Delivery address</h3><div className="fields"><input placeholder="First name"/><input placeholder="Last name"/><input className="full" placeholder="Address"/><input placeholder="City"/><input placeholder="Postal code"/><input placeholder="Country / Region"/></div></div><div className="form-section payment"><h3>Payment <small>Demo checkout</small></h3><div className="pay-icons"><span>PayPal</span><span>VISA</span><span><CreditCard size={16}/> Card</span></div><input placeholder="Card number"/><div className="fields"><input placeholder="MM / YY"/><input placeholder="CVC"/></div></div><button className="btn dark wide" onClick={()=>navigate('success')}>Pay {money(total)} <ArrowRight size={17}/></button><p className="demo-note">This is a frontend demonstration. Connect PayPal or a payment gateway server-side before accepting real payments.</p></div><div className="order-summary"><span className="eyebrow">ORDER SUMMARY</span>{cart.map(x=><div className="summary-item" key={x.id}><ProductArt product={x}/><div><b>{x.name}</b><small>Qty {x.qty}</small></div><strong>{money(x.price*x.qty)}</strong></div>)}<div className="summary-total"><span>Total</span><b>{money(total)}</b></div></div></main> }

const policies = {payment:['We accept PayPal, Visa, and major credit and debit cards through a secure payment gateway. Prices are shown in USD.'],returns:['Returns are accepted within 30 days of delivery for unused items in original condition. Contact us before sending anything back.'],cancellation:['Orders may be cancelled before dispatch by contacting our support email. Once dispatched, the returns policy applies.'],about:['綠動貿易有限公司 curates calm, considered home furnishings for everyday life. We believe a beautiful home should feel lived in, not staged.'],shipping:['Orders dispatch within 2–5 business days. Delivery estimates and tracking details are sent by email.'],tracking:['Use the tracking link in your dispatch email, or contact hongkonglvdong@outlook.com with your order number.'],privacy:['We collect only the information needed to process orders, provide support, and improve this demo store. We do not sell personal information.'],dmca:['If you believe content hosted here infringes your rights, please send a notice with the required details to hongkonglvdong@outlook.com.']};
const terms=['Agreement and eligibility','Products, prices, and availability','Orders and acceptance','Payment and billing','Delivery and risk','Returns and refunds','Cancellations','Product care and use','Intellectual property','User content','Reviews and feedback','Privacy and data protection','Third-party services','Disclaimers','Limitation of liability','Indemnification','Governing law and contact'];
function Info({type, navigate}) { const titles={payment:'付款方式',returns:'退货与退款',cancellation:'取消政策',about:'关于我们',shipping:'发货政策',tracking:'订单追踪',privacy:'隐私政策',dmca:'DMCA'}; return <main className="info"><span className="eyebrow">LVDONG HOME</span><h1>{titles[type]||'Information'}</h1><p className="lead">{policies[type]?.[0]}</p>{type==='terms'?<div className="terms">{terms.map((t,i)=><section key={t}><b>{i+1}. {t}</b><p>We aim to provide clear, fair information and a thoughtful customer experience. This section applies to purchases made through this website and should be read together with the other policies.</p></section>)}</div>:<div className="info-card"><h3>Need a hand?</h3><p>For questions about orders, delivery, payments, or returns, please contact us at <a href="mailto:hongkonglvdong@outlook.com">hongkonglvdong@outlook.com</a>.</p><button className="btn outline" onClick={()=>navigate('shop')}>Shop the collection <ArrowRight size={17}/></button></div>}</main> }

function Admin(){return <main className="admin"><span className="eyebrow">DEMO ADMIN</span><h1>Store overview</h1><p className="lead">Frontend administration preview for 綠動貿易有限公司.</p><div className="admin-login"><label>Email<input value="admin@lvdonghome.demo" readOnly/></label><label>Password<input value="LvdongDemo2026!" readOnly/></label><button className="btn dark wide">Sign in <ArrowRight size={17}/></button><small>Demo credentials only. Add server-side auth before production use.</small></div><div className="stats"><div><b>40</b><span>Products</span></div><div><b>4</b><span>Categories</span></div><div><b>12</b><span>Open orders</span></div></div></main>}

function Footer({navigate}) { const links=[['Payment methods','payment'],['Returns & refunds','returns'],['Cancellation policy','cancellation'],['About us','about'],['Shipping policy','shipping'],['Order tracking','tracking'],['Terms of service','terms'],['Privacy policy','privacy'],['DMCA','dmca']]; return <footer><div className="footer-top"><div><button className="logo light" onClick={()=>navigate('home')}>LVDONG<span>HOME</span></button><p>Thoughtful pieces for a more considered home.</p></div><div className="footer-links"><div><b>Customer care</b>{links.slice(0,3).map(x=><button key={x[1]} onClick={()=>navigate(x[1])}>{x[0]}</button>)}</div><div><b>Company & policies</b>{links.slice(3).map(x=><button key={x[1]} onClick={()=>navigate(x[1])}>{x[0]}</button>)}</div><div className="contact"><b>Contact</b><span>LVDONG TRADE CO., LIMITED</span><span>hongkonglvdong@outlook.com</span><span>707-713 Mong Kok Street,<br/>Yau Tsim Mong District,<br/>Hong Kong SAR</span></div></div></div><div className="footer-bottom"><span>© 2026 LVDONG TRADE CO., LIMITED · Registration no. Demo-registered</span><span>Secure payment · PayPal · VISA · Credit card</span></div></footer> }

function App(){const [page,setPage]=useState(window.location.hash.replace('#/','')||'home'),[cart,setCart]=useState([]),[drawer,setDrawer]=useState(false); useEffect(()=>{const onHash=()=>setPage(window.location.hash.replace('#/','')||'home');window.addEventListener('hashchange',onHash);return()=>window.removeEventListener('hashchange',onHash)},[]); const navigate=p=>{setPage(p);window.location.hash=`/${p}`;window.scrollTo(0,0)}; const add=p=>{setCart(c=>{const found=c.find(x=>x.id===p.id);return found?c.map(x=>x.id===p.id?{...x,qty:x.qty+1}:x):[...c,{...p,qty:1}]});setDrawer(true)}; const update=(id,delta)=>setCart(c=>c.map(x=>x.id===id?{...x,qty:Math.max(0,x.qty+delta)}:x).filter(x=>x.qty)); const count=cart.reduce((s,x)=>s+x.qty,0); const view=page==='home'?<Home navigate={navigate} add={add}/>:page==='shop'||categories.some(c=>c.id===page)?<Shop category={page==='shop'?null:page} add={add}/>:page==='checkout'?<Checkout cart={cart} navigate={navigate}/>:page==='admin'?<Admin/>:<Info type={page} navigate={navigate}/>; return <><Header cartCount={count} onCart={()=>setDrawer(true)} onNavigate={navigate}/>{view}<Footer navigate={navigate}/>{drawer&&<CartDrawer cart={cart} close={()=>setDrawer(false)} update={update} checkout={()=>{setDrawer(false);navigate('checkout')}}/>}</>}
createRoot(document.getElementById('root')).render(<App/>);
